### ISSUE TITLE
Atualizar Bichusp

### ISSUE THREAD

**Issue by Kazuo256** [Kazuo256/guiadobixo#83]
Na parte do Bichusp, ano e modalidade de campeões, temos:
```latex
2018 & Xadrez, Futebol de Campo F. 
```

Na parte de conquistas/títulos, tem alguns outros títulos de 2018 que estão faltando. São eles:
```latex
2018 & Copa USP & Handebol Fem. & 1º 
2018 & Jogos da Liga & Handebol Masc. & 2º
2018 & BIFE & Basquete Masc. & 1º
2018 &  Jogos da Liga & Basquete Masc. & 2º
2018 & Copa USP & Vôlei Masc. & 1º
2018 & BIFE & Vôlei Masc. & 2º 
2018 & NDU &  Vôlei Masc. & 2º 
2018 & BIFE& Natação Masc. & 2º
2018 & Jogos da Liga & Natação Masc & 2º
2018 & BIFE & Rugby Masc. & 2º 
2018 & BIFE & Futebol Campo F. & 2º
```

OBS: A AAAMat ainda não sabe a data do bichusp, então por enquanto isso vai ficar pendente.

**Comment by suhalonso** [comment]
Fiz o pull request com as atualizações

**Comment by Kazuo256** [comment]
Agora que vi no guia, parece que a tabela na seção "A Atlética / BIFE" não tá atualizada também. Alguém sabe onde foi e quem foi o campeão?

**Comment by suhalonso** [comment]
Isso a Bia atualizou, mas só no fork dela (não sei se ela está querendo atualizar mais coisas ainda ou se já era pra mandar pra gente...) https://github.com/sbeatriz/guiadobixo/commit/befef458735966b9f5b81464d0a263f31fcdae2b

**Comment by suhalonso** [comment]
Coloquei as datas do bichusp no guia (vide e-mail da Bia) e mandei um pull request com o branch da Bia
